package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"strings"

	ax "github.com/Adaptix-Framework/axc2"
	"golang.org/x/text/encoding"
	"golang.org/x/text/encoding/charmap"
	"golang.org/x/text/encoding/simplifiedchinese"
	"golang.org/x/text/transform"
)

const (
	OS_WINDOWS = 1

	TYPE_TASK = 1

	MESSAGE_INFO    = 5
	MESSAGE_ERROR   = 6
	MESSAGE_SUCCESS = 7
)

type AgentConfig struct {
	Format string `json:"format"`
	Sleep  string `json:"sleep"`
	Jitter int    `json:"jitter"`
	Debug  bool   `json:"debug"`
}

type MaverickData struct {
	Machine struct {
		OsArch    uint8  `json:"os_arch"`
		Username  string `json:"username"`
		Computer  string `json:"computer"`
		Domain    string `json:"domain"`
		Netbios   string `json:"netbios"`
		Ipaddress string `json:"ipaddress"`
		OsMajor   uint32 `json:"os_major"`
		OsMinor   uint32 `json:"os_minor"`
		OsBuild   uint32 `json:"os_build"`
	} `json:"machine"`

	Session struct {
		AgentIdStr string `json:"agent_id_str"`
		SleepTime  uint32 `json:"sleep_time"`
		Jitter     uint32 `json:"jitter"`
		Elevated   bool   `json:"elevated"`
		ProcessId  uint32 `json:"process_id"`
		ThreadId   uint32 `json:"thread_id"`
		ImgPath    string `json:"img_path"`
		ImgName    string `json:"img_name"`
		Acp        uint32 `json:"acp"`
		Oemcp      uint32 `json:"oemcp"`
	} `json:"session"`
}

func (a *MaverickData) JsonMarshal(agent *ax.AgentData, update bool) {
	var newbuff bytes.Buffer
	json.NewEncoder(&newbuff).Encode(a)
	agent.CustomData = newbuff.Bytes()
	if update {
		ModuleObject.ts.TsAgentUpdateDataPartial(
			agent.Id, map[string]interface{}{
				"custom_data": newbuff.String(),
			},
		)
	}
}

func GetWindowsVersionName(major uint32, minor uint32, build uint32) string {
	if major == 10 && minor == 0 {
		if build >= 22000 {
			return "Windows 11"
		}
		return "Windows 10"
	}
	if major == 6 && minor == 3 {
		return "Windows 8.1"
	}
	if major == 6 && minor == 2 {
		return "Windows 8"
	}
	if major == 6 && minor == 1 {
		return "Windows 7"
	}
	if major == 6 && minor == 0 {
		return "Windows Vista"
	}
	return fmt.Sprintf("Windows %d.%d (Build %d)", major, minor, build)
}

var codePageMapping = map[int]encoding.Encoding{
	437:   charmap.CodePage437,
	850:   charmap.CodePage850,
	852:   charmap.CodePage852,
	866:   charmap.CodePage866,
	936:   simplifiedchinese.GBK,
	1250:  charmap.Windows1250,
	1251:  charmap.Windows1251,
	1252:  charmap.Windows1252,
	1253:  charmap.Windows1253,
	1254:  charmap.Windows1254,
	1255:  charmap.Windows1255,
	1256:  charmap.Windows1256,
	1257:  charmap.Windows1257,
	1258:  charmap.Windows1258,
	28591: charmap.ISO8859_1,
	28592: charmap.ISO8859_2,
	65001: encoding.Nop,
}

func ConvertCpToUTF8(input string, codePage int) string {
	enc, exists := codePageMapping[codePage]
	if !exists {
		return input
	}
	reader := transform.NewReader(strings.NewReader(input), enc.NewDecoder())
	utf8Text, err := io.ReadAll(reader)
	if err != nil {
		return input
	}
	return string(utf8Text)
}

func int32_to_ipv4(ip uint) string {
	b := []byte{
		byte(ip),
		byte(ip >> 8),
		byte(ip >> 16),
		byte(ip >> 24),
	}
	return net.IP(b).String()
}

func bool_to_int(b bool) int {
	if b {
		return 1
	}
	return 0
}

func gen_shellcode_header(shellcode []byte) string {
	var sb strings.Builder

	sb.WriteString("#pragma once\n\n")
	sb.WriteString("// Autogenerated shellcode - Maverick\n")
	sb.WriteString("// DO NOT EDIT MANUALLY\n\n")
	sb.WriteString("#include <cstdint>\n\n")
	sb.WriteString("namespace Shellcode {\n\n")
	sb.WriteString(fmt.Sprintf("    constexpr size_t Size = 0x%X;\n\n", len(shellcode)))
	sb.WriteString("    __attribute__((section(\".text\")))\n")
	sb.WriteString("    const uint8_t Data[] = {\n        ")

	for i, b := range shellcode {
		if i > 0 && i%12 == 0 {
			sb.WriteString("\n        ")
		}
		sb.WriteString(fmt.Sprintf("0x%02X", b))
		if i < len(shellcode)-1 {
			sb.WriteString(", ")
		}
	}

	sb.WriteString("\n    };\n\n")
	sb.WriteString("} // namespace Shellcode\n")

	return sb.String()
}
